### ISSUE TITLE
/files not Working | FileNotFoundError: [Errno 2] No such file or directory: 'D:/'    

### ISSUE THREAD

**Issue by randomdev4578** [Strawberry-Software-Industries/SecureCloud#3]
I installed the official release of SecureCloud today on my home server, however when I go to /files I get the following error:

    Traceback (most recent call last):
      File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 2073, in wsgi_app    
        response = self.full_dispatch_request()
      File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 1518, in full_dispatch_request
        rv = self.handle_user_exception(e)
      File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 1516, in full_dispatch_request
        rv = self.dispatch_request()
      File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 1502, in dispatch_request
        return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
      File "/home/pi/SecureCloud/main.py", line 271, in files
        dir = get_dir()
      File "/home/pi/SecureCloud/main.py", line 84, in get_dir
        h = os.listdir("D:/")
    FileNotFoundError: [Errno 2] No such file or directory: 'D:/'    

OS: Raspberry Pi OS 11 (Bullseye)
Python Version: 3.10
SecureCloud Build: v1.0 Stable

**Comment by Juliandev02** [comment]
Hey @randomdev4578, 
Thanks for your issue. When debugging, I forgot to change the "D:/" (My hard disk) with the upload path. I'll get right on it and fix the bug. But then you have to download the git version (not the release version), best clone the repository.

**Comment by Juliandev02** [comment]
The bug has been fixed.
