### ISSUE TITLE
Upload Error:  '>' not supported between instances of 'int' and 'str'

### ISSUE THREAD

**Issue by randomdev4578** [Strawberry-Software-Industries/SecureCloud#5]
[2022-01-29 12:42:22,847] ERROR in app: Exception on /upload [POST]
    Traceback (most recent call last):
      File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 2073, in wsgi_app
        response = self.full_dispatch_request()
      File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 1518, in full_dispatch_request
        rv = self.handle_user_exception(e)
      File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 1516, in full_dispatch_request
        rv = self.dispatch_request()
      File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 1502, in dispatch_request
        return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
      File "/home/pi/SecureCloud/main.py", line 376, in upload
        if 'file' not in request.files:
      File "/usr/local/lib/python3.10/site-packages/werkzeug/utils.py", line 97, in __get__
        value = self.fget(obj)  # type: ignore
      File "/usr/local/lib/python3.10/site-packages/werkzeug/wrappers/request.py", line 499, in files
        self._load_form_data()
      File "/usr/local/lib/python3.10/site-packages/flask/wrappers.py", line 113, in _load_form_data
        RequestBase._load_form_data(self)
      File "/usr/local/lib/python3.10/site-packages/werkzeug/wrappers/request.py", line 285, in _load_form_data
        data = parser.parse(
      File "/usr/local/lib/python3.10/site-packages/werkzeug/formparser.py", line 252, in parse
        and content_length > self.max_content_length
    TypeError: '>' not supported between instances of 'int' and 'str'

welp..

OS: Raspberry Pi OS 11 (Bullseye)
Python Version: 3.10.2
SecureCloud Build: v1.0

**Comment by Juliandev02** [comment]
Because the maximum upload size is now set by a config file, and this is read as "str", we had to change something in the code, so that the config file is now read as "int". Thanks for your issue
